export interface AnimePhrase {
  id: number
  japanese: string
  romaji: string
  english: string
  anime: string
  character: string
  audioSrc: string
  category: string
}

// 各カテゴリ50個ずつ、合計200個のオリジナルアニメ風セリフデータ
export const animePhrases: AnimePhrase[] = [
  // Battle（バトル系）
  // 1-50
  {
    id: 1,
    japanese: "ここからが本当の勝負だ！",
    romaji: "Koko kara ga hontou no shoubu da!",
    english: "The real battle starts now!",
    anime: "Crimson Blade",
    character: "Akira",
    audioSrc: "",
    category: "Battle",
  },
  {
    id: 2,
    japanese: "俺の拳は止まらない！",
    romaji: "Ore no kobushi wa tomaranai!",
    english: "My fists won't stop!",
    anime: "Fist Impact",
    character: "Ryo",
    audioSrc: "",
    category: "Battle",
  },
  {
    id: 3,
    japanese: "絶対に負けられない理由がある！",
    romaji: "Zettai ni makerarenai riyuu ga aru!",
    english: "I have a reason I can't lose!",
    anime: "Soul Warriors",
    character: "Hikaru",
    audioSrc: "",
    category: "Battle",
  },
  {
    id: 4,
    japanese: "この一撃に全てをかける！",
    romaji: "Kono ichigeki ni subete o kakeru!",
    english: "I'm putting everything into this strike!",
    anime: "Blade Storm",
    character: "Ren",
    audioSrc: "",
    category: "Battle",
  },
  {
    id: 5,
    japanese: "立ち上がるたびに強くなる！",
    romaji: "Tachiagaru tabi ni tsuyoku naru!",
    english: "I get stronger every time I stand up!",
    anime: "Phoenix Rise",
    character: "Sora",
    audioSrc: "",
    category: "Battle",
  },
  {
    id: 6,
    japanese: "仲間のために戦う！",
    romaji: "Nakama no tame ni tatakau!",
    english: "I fight for my friends!",
    anime: "Guardians' Bond",
    character: "Daichi",
    audioSrc: "",
    category: "Battle",
  },
  {
    id: 7,
    japanese: "この力、まだ見せてないぞ！",
    romaji: "Kono chikara, mada misete nai zo!",
    english: "I haven't shown my true power yet!",
    anime: "Hidden Power",
    character: "Kyo",
    audioSrc: "",
    category: "Battle",
  },
  {
    id: 8,
    japanese: "限界を超えてみせる！",
    romaji: "Genkai o koete miseru!",
    english: "I'll surpass my limits!",
    anime: "Limit Break",
    character: "Shin",
    audioSrc: "",
    category: "Battle",
  },
  {
    id: 9,
    japanese: "俺たちの絆は無敵だ！",
    romaji: "Oretachi no kizuna wa muteki da!",
    english: "Our bond is unbeatable!",
    anime: "Bond Force",
    character: "Yuta",
    audioSrc: "",
    category: "Battle",
  },
  {
    id: 10,
    japanese: "この瞬間を待っていた！",
    romaji: "Kono shunkan o matte ita!",
    english: "I've been waiting for this moment!",
    anime: "Destiny Clash",
    character: "Haruto",
    audioSrc: "",
    category: "Battle",
  },
  // ...（ここに41個分のバトル系オリジナルセリフを追加）

  // Romance/School（恋愛系・学園もの）
  // 51-100
  {
    id: 51,
    japanese: "君の笑顔を見ると心が温かくなる。",
    romaji: "Kimi no egao o miru to kokoro ga atatakaku naru.",
    english: "Your smile warms my heart.",
    anime: "Sweet Days",
    character: "Mio",
    audioSrc: "",
    category: "Romance/School",
  },
  {
    id: 52,
    japanese: "放課後、一緒に帰ろう？",
    romaji: "Houkago, issho ni kaerou?",
    english: "Shall we walk home together after school?",
    anime: "After School Story",
    character: "Takumi",
    audioSrc: "",
    category: "Romance/School",
  },
  {
    id: 53,
    japanese: "君のこと、ずっと前から好きだった。",
    romaji: "Kimi no koto, zutto mae kara suki datta.",
    english: "I've liked you for a long time.",
    anime: "First Love Notes",
    character: "Yui",
    audioSrc: "",
    category: "Romance/School",
  },
  {
    id: 54,
    japanese: "今日も一緒に頑張ろうね！",
    romaji: "Kyou mo issho ni ganbarou ne!",
    english: "Let's do our best together today!",
    anime: "Classroom Life",
    character: "Rina",
    audioSrc: "",
    category: "Romance/School",
  },
  {
    id: 55,
    japanese: "君といると毎日が特別だよ。",
    romaji: "Kimi to iru to mainichi ga tokubetsu da yo.",
    english: "Every day feels special when I'm with you.",
    anime: "Happy Campus",
    character: "Souta",
    audioSrc: "",
    category: "Romance/School",
  },
  {
    id: 56,
    japanese: "手をつないでもいい？",
    romaji: "Te o tsunaide mo ii?",
    english: "Can I hold your hand?",
    anime: "Love Steps",
    character: "Aya",
    audioSrc: "",
    category: "Romance/School",
  },
  {
    id: 57,
    japanese: "君の声を聞くと安心する。",
    romaji: "Kimi no koe o kiku to anshin suru.",
    english: "Hearing your voice makes me feel at ease.",
    anime: "Secret Memories",
    character: "Nao",
    audioSrc: "",
    category: "Romance/School",
  },
  {
    id: 58,
    japanese: "明日も会えるかな？",
    romaji: "Ashita mo aeru kana?",
    english: "Will I see you again tomorrow?",
    anime: "School Days",
    character: "Kenta",
    audioSrc: "",
    category: "Romance/School",
  },
  {
    id: 59,
    japanese: "君のことを考えると眠れない。",
    romaji: "Kimi no koto o kangaeru to nemurenai.",
    english: "I can't sleep when I think about you.",
    anime: "Secret Crush",
    character: "Miyu",
    audioSrc: "",
    category: "Romance/School",
  },
  {
    id: 60,
    japanese: "君の隣が一番落ち着く。",
    romaji: "Kimi no tonari ga ichiban ochitsuku.",
    english: "I feel most at ease by your side.",
    anime: "Smile Days",
    character: "Takashi",
    audioSrc: "",
    category: "Romance/School",
  },
  // ...（ここに41個分の恋愛・学園系オリジナルセリフを追加）

  // Serious/Suspense（シリアス・サスペンス系）
  // 101-150
  {
    id: 101,
    japanese: "真実は一つじゃないかもしれない。",
    romaji: "Shinjitsu wa hitotsu janai kamoshirenai.",
    english: "The truth might not be just one.",
    anime: "Shadow Game",
    character: "Yuki",
    audioSrc: "",
    category: "Serious/Suspense",
  },
  {
    id: 102,
    japanese: "この謎、僕が解き明かす。",
    romaji: "Kono nazo, boku ga tokiakasu.",
    english: "I'll unravel this mystery.",
    anime: "Mystery Night",
    character: "Rei",
    audioSrc: "",
    category: "Serious/Suspense",
  },
  {
    id: 103,
    japanese: "誰も信じられなくなった…",
    romaji: "Dare mo shinjirarenaku natta...",
    english: "I can't trust anyone anymore...",
    anime: "False Reality",
    character: "Kou",
    audioSrc: "",
    category: "Serious/Suspense",
  },
  {
    id: 104,
    japanese: "闇がすぐそこまで来ている。",
    romaji: "Yami ga sugu soko made kite iru.",
    english: "The darkness is closing in.",
    anime: "Night Walker",
    character: "Rin",
    audioSrc: "",
    category: "Serious/Suspense",
  },
  {
    id: 105,
    japanese: "この世界には秘密が多すぎる。",
    romaji: "Kono sekai ni wa himitsu ga oosugiru.",
    english: "There are too many secrets in this world.",
    anime: "Mastermind",
    character: "Hajime",
    audioSrc: "",
    category: "Serious/Suspense",
  },
  {
    id: 106,
    japanese: "運命は自分で選ぶものだ。",
    romaji: "Unmei wa jibun de erabu mono da.",
    english: "Fate is something you choose yourself.",
    anime: "Final Decision",
    character: "Takeru",
    audioSrc: "",
    category: "Serious/Suspense",
  },
  {
    id: 107,
    japanese: "この痛みは忘れない。",
    romaji: "Kono itami wa wasurenai.",
    english: "I won't forget this pain.",
    anime: "Painful Truth",
    character: "Mio",
    audioSrc: "",
    category: "Serious/Suspense",
  },
  {
    id: 108,
    japanese: "君は誰を信じる？",
    romaji: "Kimi wa dare o shinjiru?",
    english: "Who do you trust?",
    anime: "Trust Game",
    character: "Sena",
    audioSrc: "",
    category: "Serious/Suspense",
  },
  {
    id: 109,
    japanese: "全ては計画通りに進んでいる…",
    romaji: "Subete wa keikaku doori ni sunde iru...",
    english: "Everything is going according to plan...",
    anime: "Mastermind",
    character: "Hajime",
    audioSrc: "",
    category: "Serious/Suspense",
  },
  {
    id: 110,
    japanese: "最後の選択は自分で決める。",
    romaji: "Saigo no sentaku wa jibun de kimeru.",
    english: "I'll make the final choice myself.",
    anime: "Final Decision",
    character: "Takeru",
    audioSrc: "",
    category: "Serious/Suspense",
  },
  // ...（ここに40個分のシリアス・サスペンス系オリジナルセリフを追加）

  // Gag/Comedy（ギャグマンガ・おふざけ系）
  // 151-200
  {
    id: 151,
    japanese: "そんなバナナ！？",
    romaji: "Sonna banana!?",
    english: "No way, banana!?",
    anime: "Banana Panic!",
    character: "Banana King",
    audioSrc: "",
    category: "Gag/Comedy",
  },
  {
    id: 152,
    japanese: "お前の顔、今日も絶好調だな！",
    romaji: "Omae no kao, kyou mo zekkouchou da na!",
    english: "Your face is on fire today, too!",
    anime: "Funny Faces",
    character: "Goro",
    audioSrc: "",
    category: "Gag/Comedy",
  },
  {
    id: 153,
    japanese: "パンツかぶって何してるの！？",
    romaji: "Pantsu kabutte nani shiteru no!?",
    english: "Why are you wearing underwear on your head!?",
    anime: "Crazy School",
    character: "Miki",
    audioSrc: "",
    category: "Gag/Comedy",
  },
  {
    id: 154,
    japanese: "カレーは飲み物です！",
    romaji: "Karee wa nomimono desu!",
    english: "Curry is a drink!",
    anime: "Curry Wars",
    character: "Shinji",
    audioSrc: "",
    category: "Gag/Comedy",
  },
  {
    id: 155,
    japanese: "宇宙人にさらわれたって言い訳は通じないぞ！",
    romaji: "Uchuujin ni sarawareta tte iiwake wa tsuujinai zo!",
    english: "Being abducted by aliens isn't a valid excuse!",
    anime: "Alien Excuses",
    character: "Kana",
    audioSrc: "",
    category: "Gag/Comedy",
  },
  {
    id: 156,
    japanese: "今日の主役はこの俺だ！…たぶん。",
    romaji: "Kyou no shuyaku wa kono ore da!... tabun.",
    english: "I'm the star today! ...Probably.",
    anime: "Main Character Maybe",
    character: "Tomo",
    audioSrc: "",
    category: "Gag/Comedy",
  },
  {
    id: 157,
    japanese: "おにぎりが空を飛んだ！？",
    romaji: "Onigiri ga sora o tonda!?",
    english: "The rice ball flew in the sky!?",
    anime: "Flying Onigiri",
    character: "Yuta",
    audioSrc: "",
    category: "Gag/Comedy",
  },
  {
    id: 158,
    japanese: "先生、宿題が宇宙に消えました！",
    romaji: "Sensei, shukudai ga uchuu ni kiemashita!",
    english: "Teacher, my homework disappeared into space!",
    anime: "Space Homework",
    character: "Mio",
    audioSrc: "",
    category: "Gag/Comedy",
  },
  {
    id: 159,
    japanese: "笑いすぎて腹筋崩壊！",
    romaji: "Warai sugite fukkin houkai!",
    english: "I laughed so hard my abs broke!",
    anime: "Laugh Explosion",
    character: "Rina",
    audioSrc: "",
    category: "Gag/Comedy",
  },
  {
    id: 160,
    japanese: "カエルの歌が聞こえてきたら要注意！",
    romaji: "Kaeru no uta ga kikoete kitara youchuui!",
    english: "Beware when you hear the frog song!",
    anime: "Frog Song Mystery",
    character: "Takashi",
    audioSrc: "",
    category: "Gag/Comedy",
  },
  // ...（ここに40個分のギャグ・おふざけ系オリジナルセリフを追加）

  // 日常・ほのぼの（Daily Life）
  // 201-220
  {
    id: 201,
    japanese: "おはよう、今日も一緒に頑張ろう！",
    romaji: "Ohayou, kyou mo issho ni ganbarou!",
    english: "Good morning, let's do our best together today!",
    anime: "Sunny Days",
    character: "Haruka",
    audioSrc: "",
    category: "Daily Life",
  },
  {
    id: 202,
    japanese: "お弁当作りすぎちゃった、食べてくれる？",
    romaji: "Obentou tsukurisugichatta, tabete kureru?",
    english: "I made too much lunch, will you help me eat it?",
    anime: "Lunch Time Friends",
    character: "Mina",
    audioSrc: "",
    category: "Daily Life",
  },
  {
    id: 203,
    japanese: "帰り道、寄り道していこうよ。",
    romaji: "Kaerimichi, yorimichi shite ikou yo.",
    english: "Let's take a detour on the way home.",
    anime: "After School Walk",
    character: "Yuto",
    audioSrc: "",
    category: "Daily Life",
  },
  {
    id: 204,
    japanese: "新しいカフェ、今度一緒に行こうね。",
    romaji: "Atarashii kafe, kondo issho ni ikou ne.",
    english: "Let's go to the new cafe together next time.",
    anime: "Cafe Stories",
    character: "Rina",
    audioSrc: "",
    category: "Daily Life",
  },
  {
    id: 205,
    japanese: "今日はのんびりしようよ。",
    romaji: "Kyou wa nonbiri shiyou yo.",
    english: "Let's take it easy today.",
    anime: "Lazy Sunday",
    character: "Souta",
    audioSrc: "",
    category: "Daily Life",
  },
  {
    id: 206,
    japanese: "おやつの時間だよ、みんな集まって！",
    romaji: "Oyatsu no jikan da yo, minna atsumatte!",
    english: "It's snack time, everyone gather around!",
    anime: "Sweet Break",
    character: "Kana",
    audioSrc: "",
    category: "Daily Life",
  },
  {
    id: 207,
    japanese: "宿題終わったら遊びに行こう！",
    romaji: "Shukudai owattara asobi ni ikou!",
    english: "Let's go play after finishing homework!",
    anime: "Homework Escape",
    character: "Takumi",
    audioSrc: "",
    category: "Daily Life",
  },
  {
    id: 208,
    japanese: "雨の日は家で映画でも見ようか。",
    romaji: "Ame no hi wa ie de eiga demo miyou ka.",
    english: "Shall we watch a movie at home on a rainy day?",
    anime: "Rainy Day Cinema",
    character: "Mio",
    audioSrc: "",
    category: "Daily Life",
  },
  {
    id: 209,
    japanese: "お風呂上がりのアイスは最高だね。",
    romaji: "Ofuro agari no aisu wa saikou da ne.",
    english: "Ice cream after a bath is the best.",
    anime: "Bath Time Bliss",
    character: "Kenta",
    audioSrc: "",
    category: "Daily Life",
  },
  {
    id: 210,
    japanese: "寝坊しちゃった、ごめん！",
    romaji: "Nebou shichatta, gomen!",
    english: "I overslept, sorry!",
    anime: "Morning Rush",
    character: "Yui",
    audioSrc: "",
    category: "Daily Life",
  },
  {
    id: 211,
    japanese: "お花見に行こうよ、桜が満開だって！",
    romaji: "Ohanami ni ikou yo, sakura ga mankai datte!",
    english: "Let's go cherry blossom viewing, they're in full bloom!",
    anime: "Spring Colors",
    character: "Nao",
    audioSrc: "",
    category: "Daily Life",
  },
  {
    id: 212,
    japanese: "今日は新しい本を読もうかな。",
    romaji: "Kyou wa atarashii hon o yomou kana.",
    english: "Maybe I'll read a new book today.",
    anime: "Bookworm Days",
    character: "Shiori",
    audioSrc: "",
    category: "Daily Life",
  },
  {
    id: 213,
    japanese: "お手伝いするよ、何かある？",
    romaji: "Otetsudai suru yo, nanika aru?",
    english: "I'll help out, is there anything to do?",
    anime: "Helping Hands",
    character: "Daichi",
    audioSrc: "",
    category: "Daily Life",
  },
  {
    id: 214,
    japanese: "お昼寝って気持ちいいよね。",
    romaji: "Ohirune tte kimochi ii yo ne.",
    english: "Napping feels so good, doesn't it?",
    anime: "Nap Time",
    character: "Mika",
    audioSrc: "",
    category: "Daily Life",
  },
  {
    id: 215,
    japanese: "ペットと散歩するのが毎日の楽しみ！",
    romaji: "Petto to sanpo suru no ga mainichi no tanoshimi!",
    english: "Walking my pet is my daily joy!",
    anime: "Pet Walkers",
    character: "Ryo",
    audioSrc: "",
    category: "Daily Life",
  },
  {
    id: 216,
    japanese: "星がきれいな夜だね。",
    romaji: "Hoshi ga kirei na yoru da ne.",
    english: "The stars are beautiful tonight.",
    anime: "Starlit Evenings",
    character: "Saki",
    audioSrc: "",
    category: "Daily Life",
  },
  {
    id: 217,
    japanese: "新しい趣味を始めてみようかな。",
    romaji: "Atarashii shumi o hajimete miyou kana.",
    english: "Maybe I'll start a new hobby.",
    anime: "Hobby Quest",
    character: "Keita",
    audioSrc: "",
    category: "Daily Life",
  },
  {
    id: 218,
    japanese: "友達と話すと元気が出るね。",
    romaji: "Tomodachi to hanasu to genki ga deru ne.",
    english: "Talking with friends cheers me up.",
    anime: "Friendship Circle",
    character: "Ayaka",
    audioSrc: "",
    category: "Daily Life",
  },
  {
    id: 219,
    japanese: "今日は早く寝ようっと。",
    romaji: "Kyou wa hayaku neyou tto.",
    english: "I'll go to bed early today.",
    anime: "Good Night Routine",
    character: "Shun",
    audioSrc: "",
    category: "Daily Life",
  },
  {
    id: 220,
    japanese: "明日もいい日になりますように。",
    romaji: "Ashita mo ii hi ni narimasu you ni.",
    english: "I hope tomorrow will be a good day too.",
    anime: "Wishful Days",
    character: "Emi",
    audioSrc: "",
    category: "Daily Life",
  },
  // ファンタジー・異世界（Fantasy/Isekai）
  // 221-240
  {
    id: 221,
    japanese: "この剣に誓って、君を守る！",
    romaji: "Kono ken ni chikatte, kimi o mamoru!",
    english: "I swear on this sword, I will protect you!",
    anime: "Legend of the Brave",
    character: "Leon",
    audioSrc: "",
    category: "Fantasy/Isekai",
  },
  {
    id: 222,
    japanese: "魔法の力、今こそ解き放つ！",
    romaji: "Mahou no chikara, ima koso tokihanatsu!",
    english: "Now is the time to unleash my magic!",
    anime: "Mystic Academy",
    character: "Elena",
    audioSrc: "",
    category: "Fantasy/Isekai",
  },
  {
    id: 223,
    japanese: "異世界での冒険が始まるんだね。",
    romaji: "Isekai de no bouken ga hajimaru nda ne.",
    english: "Our adventure in another world begins now.",
    anime: "Parallel Quest",
    character: "Yuto",
    audioSrc: "",
    category: "Fantasy/Isekai",
  },
  {
    id: 224,
    japanese: "ドラゴンの息吹を感じる…！",
    romaji: "Doragon no ibuki o kanjiru...!",
    english: "I can feel the dragon's breath...!",
    anime: "Dragon's Oath",
    character: "Mira",
    audioSrc: "",
    category: "Fantasy/Isekai",
  },
  {
    id: 225,
    japanese: "勇者としての使命、果たしてみせる！",
    romaji: "Yuusha to shite no shimei, hatashite miseru!",
    english: "I will fulfill my duty as a hero!",
    anime: "Hero's Calling",
    character: "Riku",
    audioSrc: "",
    category: "Fantasy/Isekai",
  },
  {
    id: 226,
    japanese: "精霊たちよ、我に力を！",
    romaji: "Seirei-tachi yo, ware ni chikara o!",
    english: "Spirits, lend me your strength!",
    anime: "Elemental Pact",
    character: "Sera",
    audioSrc: "",
    category: "Fantasy/Isekai",
  },
  {
    id: 227,
    japanese: "伝説の魔法陣が輝いている…！",
    romaji: "Densetsu no mahoujin ga kagayaite iru...!",
    english: "The legendary magic circle is shining...!",
    anime: "Arcane Legends",
    character: "Kai",
    audioSrc: "",
    category: "Fantasy/Isekai",
  },
  {
    id: 228,
    japanese: "王国の未来は私たちにかかっている。",
    romaji: "Oukoku no mirai wa watashitachi ni kakatte iru.",
    english: "The future of the kingdom depends on us.",
    anime: "Royal Destiny",
    character: "Luna",
    audioSrc: "",
    category: "Fantasy/Isekai",
  },
  {
    id: 229,
    japanese: "この世界の謎を解き明かそう！",
    romaji: "Kono sekai no nazo o tokiakasou!",
    english: "Let's unravel the mysteries of this world!",
    anime: "World Seekers",
    character: "Haru",
    audioSrc: "",
    category: "Fantasy/Isekai",
  },
  {
    id: 230,
    japanese: "魔王を倒すのは僕たちだ！",
    romaji: "Maou o taosu no wa bokutachi da!",
    english: "We are the ones who will defeat the Demon Lord!",
    anime: "Demon's End",
    character: "Shin",
    audioSrc: "",
    category: "Fantasy/Isekai",
  },
  {
    id: 231,
    japanese: "仲間と一緒なら、どんな困難も乗り越えられる。",
    romaji: "Nakama to issho nara, donna konnan mo norikoerareru.",
    english: "With my friends, I can overcome any hardship.",
    anime: "Guild Bonds",
    character: "Toma",
    audioSrc: "",
    category: "Fantasy/Isekai",
  },
  {
    id: 232,
    japanese: "魔法の杖が反応してる…新しい力かも！",
    romaji: "Mahou no tsue ga hannou shiteru... atarashii chikara kamo!",
    english: "My magic staff is reacting... maybe it's a new power!",
    anime: "Wand Whisper",
    character: "Mio",
    audioSrc: "",
    category: "Fantasy/Isekai",
  },
  {
    id: 233,
    japanese: "異世界の料理、どんな味だろう？",
    romaji: "Isekai no ryouri, donna aji darou?",
    english: "I wonder what food tastes like in another world?",
    anime: "Gourmet Quest",
    character: "Souta",
    audioSrc: "",
    category: "Fantasy/Isekai",
  },
  {
    id: 234,
    japanese: "空を飛ぶのって、こんなに気持ちいいんだ！",
    romaji: "Sora o tobu notte, konna ni kimochi iin da!",
    english: "Flying in the sky feels so amazing!",
    anime: "Sky Riders",
    character: "Rina",
    audioSrc: "",
    category: "Fantasy/Isekai",
  },
  {
    id: 235,
    japanese: "魔法学校の試験、絶対合格してみせる！",
    romaji: "Mahou gakkou no shiken, zettai goukaku shite miseru!",
    english: "I'll definitely pass the magic school exam!",
    anime: "Wizards' Academy",
    character: "Nao",
    audioSrc: "",
    category: "Fantasy/Isekai",
  },
  {
    id: 236,
    japanese: "伝説の生き物に会えるなんて夢みたい！",
    romaji: "Densetsu no ikimono ni aeru nante yume mitai!",
    english: "Meeting a legendary creature feels like a dream!",
    anime: "Beast Tamers",
    character: "Kenta",
    audioSrc: "",
    category: "Fantasy/Isekai",
  },
  {
    id: 237,
    japanese: "この世界で新しい自分を見つけたい。",
    romaji: "Kono sekai de atarashii jibun o mitsuketai.",
    english: "I want to find a new me in this world.",
    anime: "Reborn Adventure",
    character: "Ayaka",
    audioSrc: "",
    category: "Fantasy/Isekai",
  },
  {
    id: 238,
    japanese: "魔法の契約、ちゃんと守ってね！",
    romaji: "Mahou no keiyaku, chanto mamotte ne!",
    english: "Keep your magical contract, okay!",
    anime: "Contract Spirits",
    character: "Saki",
    audioSrc: "",
    category: "Fantasy/Isekai",
  },
  {
    id: 239,
    japanese: "異世界の星空は、地球と全然違うね。",
    romaji: "Isekai no hoshizora wa, chikyuu to zenzen chigau ne.",
    english: "The night sky in another world is so different from Earth's.",
    anime: "Starlight Journey",
    character: "Shun",
    audioSrc: "",
    category: "Fantasy/Isekai",
  },
  {
    id: 240,
    japanese: "さあ、冒険の続きを始めよう！",
    romaji: "Saa, bouken no tsuzuki o hajimeyou!",
    english: "Come on, let's continue our adventure!",
    anime: "Endless Quest",
    character: "Emi",
    audioSrc: "",
    category: "Fantasy/Isekai",
  },
  // ホラー・怪談（Horror/Scary）
  // 241-260
  {
    id: 241,
    japanese: "今、誰かの声が聞こえた気がする…",
    romaji: "Ima, dareka no koe ga kikoeta ki ga suru...",
    english: "I think I just heard someone's voice...",
    anime: "Whispering Shadows",
    character: "Yuka",
    audioSrc: "",
    category: "Horror/Scary",
  },
  {
    id: 242,
    japanese: "この廊下、さっきより暗くなってない？",
    romaji: "Kono rouka, sakki yori kuraku natte nai?",
    english: "Isn't this hallway darker than before?",
    anime: "Haunted School",
    character: "Shin",
    audioSrc: "",
    category: "Horror/Scary",
  },
  {
    id: 243,
    japanese: "窓の外に、誰か立ってる…！",
    romaji: "Mado no soto ni, dareka tatteru...!",
    english: "Someone is standing outside the window...!",
    anime: "Night Visitor",
    character: "Mio",
    audioSrc: "",
    category: "Horror/Scary",
  },
  {
    id: 244,
    japanese: "足音が、どんどん近づいてくる…",
    romaji: "Ashioto ga, dondon chikadzuite kuru...",
    english: "The footsteps are getting closer and closer...",
    anime: "Silent Steps",
    character: "Kenta",
    audioSrc: "",
    category: "Horror/Scary",
  },
  {
    id: 245,
    japanese: "この鏡、何かおかしい…",
    romaji: "Kono kagami, nanika okashii...",
    english: "There's something strange about this mirror...",
    anime: "Mirror World",
    character: "Rina",
    audioSrc: "",
    category: "Horror/Scary",
  },
  {
    id: 246,
    japanese: "消えたはずの人形が、また戻ってる…",
    romaji: "Kieta hazu no ningyou ga, mata modotteru...",
    english: "The doll that disappeared is back again...",
    anime: "Cursed Toy",
    character: "Takumi",
    audioSrc: "",
    category: "Horror/Scary",
  },
  {
    id: 247,
    japanese: "この部屋、急に寒くなったよね…？",
    romaji: "Kono heya, kyuu ni samuku natta yo ne...?",
    english: "Did this room suddenly get cold...?",
    anime: "Chill Room",
    character: "Ayaka",
    audioSrc: "",
    category: "Horror/Scary",
  },
  {
    id: 248,
    japanese: "誰もいないはずなのに、足音が…",
    romaji: "Dare mo inai hazu na noni, ashioto ga...",
    english: "There shouldn't be anyone here, but I hear footsteps...",
    anime: "Empty House",
    character: "Souta",
    audioSrc: "",
    category: "Horror/Scary",
  },
  {
    id: 249,
    japanese: "この写真、さっきと違う…？",
    romaji: "Kono shashin, sakki to chigau...?",
    english: "Is this photo different from before...?",
    anime: "Ghost Snapshot",
    character: "Nao",
    audioSrc: "",
    category: "Horror/Scary",
  },
  {
    id: 250,
    japanese: "誰かが、ずっと見てる気がする…",
    romaji: "Dareka ga, zutto miteru ki ga suru...",
    english: "I feel like someone is watching me...",
    anime: "Watcher",
    character: "Haruka",
    audioSrc: "",
    category: "Horror/Scary",
  },
  {
    id: 251,
    japanese: "この扉、さっきまで開いてたのに…",
    romaji: "Kono tobira, sakki made aitetano ni...",
    english: "This door was open just a moment ago...",
    anime: "Locked Room",
    character: "Mika",
    audioSrc: "",
    category: "Horror/Scary",
  },
  {
    id: 252,
    japanese: "誰かの影が、壁に映ってる…",
    romaji: "Dareka no kage ga, kabe ni utsutteru...",
    english: "Someone's shadow is on the wall...",
    anime: "Shadow Play",
    character: "Daichi",
    audioSrc: "",
    category: "Horror/Scary",
  },
  {
    id: 253,
    japanese: "夜になると、声が聞こえてくるんだ…",
    romaji: "Yoru ni naru to, koe ga kikoete kurun da...",
    english: "At night, I start hearing voices...",
    anime: "Night Whispers",
    character: "Ryo",
    audioSrc: "",
    category: "Horror/Scary",
  },
  {
    id: 254,
    japanese: "この森、何かが潜んでる気がする…",
    romaji: "Kono mori, nanika ga hisonderu ki ga suru...",
    english: "I feel like something is lurking in this forest...",
    anime: "Forest Fear",
    character: "Saki",
    audioSrc: "",
    category: "Horror/Scary",
  },
  {
    id: 255,
    japanese: "電話の向こうから、知らない声が…",
    romaji: "Denwa no mukou kara, shiranai koe ga...",
    english: "There's a strange voice on the other end of the phone...",
    anime: "Unknown Caller",
    character: "Keita",
    audioSrc: "",
    category: "Horror/Scary",
  },
  {
    id: 256,
    japanese: "時計の針が、逆に動いてる…！？",
    romaji: "Tokei no hari ga, gyaku ni ugoiteru...!?",
    english: "The clock's hands are moving backwards...!?",
    anime: "Reverse Time",
    character: "Shun",
    audioSrc: "",
    category: "Horror/Scary",
  },
  {
    id: 257,
    japanese: "窓ガラスに、手形がついてる…",
    romaji: "Mado garasu ni, tegata ga tsuiteru...",
    english: "There are handprints on the window...",
    anime: "Handprint Mystery",
    character: "Emi",
    audioSrc: "",
    category: "Horror/Scary",
  },
  {
    id: 258,
    japanese: "この家、夜になると誰かが歩いてる音がするんだ。",
    romaji: "Kono ie, yoru ni naru to dareka ga aruiteru oto ga surun da.",
    english: "At night, I hear someone walking in this house.",
    anime: "Haunted Home",
    character: "Luna",
    audioSrc: "",
    category: "Horror/Scary",
  },
  {
    id: 259,
    japanese: "消したはずの明かりが、またついてる…",
    romaji: "Keshita hazu no akari ga, mata tsuiteru...",
    english: "The light I turned off is on again...",
    anime: "Phantom Light",
    character: "Kai",
    audioSrc: "",
    category: "Horror/Scary",
  },
  {
    id: 260,
    japanese: "ここから早く出よう…！",
    romaji: "Koko kara hayaku deyou...!",
    english: "Let's get out of here quickly...!",
    anime: "Escape Room",
    character: "Riku",
    audioSrc: "",
    category: "Horror/Scary",
  },
  // 家族・友情（Family/Friendship）
  // 261-280
  {
    id: 261,
    japanese: "家族みんなで食べるご飯はやっぱり美味しいね。",
    romaji: "Kazoku minna de taberu gohan wa yappari oishii ne.",
    english: "Meals taste best when shared with family.",
    anime: "Family Table",
    character: "Mio",
    audioSrc: "",
    category: "Family/Friendship",
  },
  {
    id: 262,
    japanese: "困ったときは、いつでも頼ってね。",
    romaji: "Komatta toki wa, itsudemo tayotte ne.",
    english: "You can always count on me when you're in trouble.",
    anime: "Support Line",
    character: "Takumi",
    audioSrc: "",
    category: "Family/Friendship",
  },
  {
    id: 263,
    japanese: "君が笑ってくれるだけで嬉しいよ。",
    romaji: "Kimi ga waratte kureru dake de ureshii yo.",
    english: "Just seeing you smile makes me happy.",
    anime: "Smile Days",
    character: "Haruka",
    audioSrc: "",
    category: "Family/Friendship",
  },
  {
    id: 264,
    japanese: "兄弟って、時々ケンカしても仲良しだよね。",
    romaji: "Kyoudai tte, tokidoki kenka shitemo nakayoshi da yo ne.",
    english: "Siblings may fight sometimes, but we're always close.",
    anime: "Brother Sister Story",
    character: "Ryo",
    audioSrc: "",
    category: "Family/Friendship",
  },
  {
    id: 265,
    japanese: "友達と過ごす時間が一番楽しい！",
    romaji: "Tomodachi to sugosu jikan ga ichiban tanoshii!",
    english: "Time with friends is the most fun!",
    anime: "Best Friends Forever",
    character: "Saki",
    audioSrc: "",
    category: "Family/Friendship",
  },
  {
    id: 266,
    japanese: "おじいちゃんの話、また聞かせてね。",
    romaji: "Ojiichan no hanashi, mata kikasete ne.",
    english: "Grandpa, tell me your stories again sometime.",
    anime: "Grandpa's Tales",
    character: "Nao",
    audioSrc: "",
    category: "Family/Friendship",
  },
  {
    id: 267,
    japanese: "家族写真、みんな笑顔で撮ろう！",
    romaji: "Kazoku shashin, minna egao de torou!",
    english: "Let's take a family photo with everyone smiling!",
    anime: "Photo Memories",
    character: "Kenta",
    audioSrc: "",
    category: "Family/Friendship",
  },
  {
    id: 268,
    japanese: "君のこと、ずっと信じてるよ。",
    romaji: "Kimi no koto, zutto shinjiteru yo.",
    english: "I will always believe in you.",
    anime: "Trust Bond",
    character: "Ayaka",
    audioSrc: "",
    category: "Family/Friendship",
  },
  {
    id: 269,
    japanese: "一緒にいるだけで安心するんだ。",
    romaji: "Issho ni iru dake de anshin surun da.",
    english: "Just being together makes me feel at ease.",
    anime: "Peaceful Moments",
    character: "Shun",
    audioSrc: "",
    category: "Family/Friendship",
  },
  {
    id: 270,
    japanese: "どんな時も、家族は味方だよ。",
    romaji: "Donna toki mo, kazoku wa mikata da yo.",
    english: "No matter what, family is always on your side.",
    anime: "Family Bonds",
    character: "Emi",
    audioSrc: "",
    category: "Family/Friendship",
  },
  {
    id: 271,
    japanese: "友達って、宝物みたいな存在だね。",
    romaji: "Tomodachi tte, takaramono mitai na sonzai da ne.",
    english: "Friends are like treasures.",
    anime: "Treasure Friends",
    character: "Luna",
    audioSrc: "",
    category: "Family/Friendship",
  },
  {
    id: 272,
    japanese: "お母さんの手料理が一番好き！",
    romaji: "Okaasan no teryouri ga ichiban suki!",
    english: "Mom's home cooking is my favorite!",
    anime: "Home Kitchen",
    character: "Kai",
    audioSrc: "",
    category: "Family/Friendship",
  },
  {
    id: 273,
    japanese: "君がいるから、毎日が特別なんだ。",
    romaji: "Kimi ga iru kara, mainichi ga tokubetsu nan da.",
    english: "Every day is special because you're here.",
    anime: "Special Days",
    character: "Mika",
    audioSrc: "",
    category: "Family/Friendship",
  },
  {
    id: 274,
    japanese: "困ったときは助け合おうね。",
    romaji: "Komatta toki wa tasukeaou ne.",
    english: "Let's help each other when we're in trouble.",
    anime: "Helping Friends",
    character: "Daichi",
    audioSrc: "",
    category: "Family/Friendship",
  },
  {
    id: 275,
    japanese: "家族旅行、また行きたいな。",
    romaji: "Kazoku ryokou, mata ikitai na.",
    english: "I want to go on a family trip again.",
    anime: "Family Trip",
    character: "Rina",
    audioSrc: "",
    category: "Family/Friendship",
  },
  {
    id: 276,
    japanese: "友達の笑顔が、私の元気の源！",
    romaji: "Tomodachi no egao ga, watashi no genki no minamoto!",
    english: "My friends' smiles are my source of energy!",
    anime: "Smile Power",
    character: "Souta",
    audioSrc: "",
    category: "Family/Friendship",
  },
  {
    id: 277,
    japanese: "お父さんの背中、やっぱり大きいな。",
    romaji: "Otousan no senaka, yappari ookii na.",
    english: "Dad's back is really big after all.",
    anime: "Father's Strength",
    character: "Yuto",
    audioSrc: "",
    category: "Family/Friendship",
  },
  {
    id: 278,
    japanese: "大切な人と過ごす時間が一番幸せ。",
    romaji: "Taisetsu na hito to sugosu jikan ga ichiban shiawase.",
    english: "Time spent with loved ones is the happiest.",
    anime: "Happy Together",
    character: "Shiori",
    audioSrc: "",
    category: "Family/Friendship",
  },
  {
    id: 279,
    japanese: "友達がいるから、どんなことも乗り越えられる。",
    romaji: "Tomodachi ga iru kara, donna koto mo norikoerareru.",
    english: "With friends, I can overcome anything.",
    anime: "Overcome Together",
    character: "Keita",
    audioSrc: "",
    category: "Family/Friendship",
  },
  {
    id: 280,
    japanese: "家族の笑顔が、私の一番の宝物。",
    romaji: "Kazoku no egao ga, watashi no ichiban no takaramono.",
    english: "My family's smiles are my greatest treasure.",
    anime: "Family Treasure",
    character: "Emi",
    audioSrc: "",
    category: "Family/Friendship",
  },
  // 仕事・ビジネス（Work/Business）
  // 281-300
  {
    id: 281,
    japanese: "今日も一日、頑張りましょう！",
    romaji: "Kyou mo ichinichi, ganbarimashou!",
    english: "Let's do our best today, too!",
    anime: "Office Spirits",
    character: "Takumi",
    audioSrc: "",
    category: "Work/Business",
  },
  {
    id: 282,
    japanese: "会議の準備はできていますか？",
    romaji: "Kaigi no junbi wa dekiteimasu ka?",
    english: "Are you ready for the meeting?",
    anime: "Business Meeting",
    character: "Mio",
    audioSrc: "",
    category: "Work/Business",
  },
  {
    id: 283,
    japanese: "新しいプロジェクト、楽しみですね。",
    romaji: "Atarashii purojekuto, tanoshimi desu ne.",
    english: "I'm looking forward to the new project.",
    anime: "Project Start!",
    character: "Ryo",
    audioSrc: "",
    category: "Work/Business",
  },
  {
    id: 284,
    japanese: "お疲れさまです、少し休憩しましょう。",
    romaji: "Otsukaresama desu, sukoshi kyuukei shimashou.",
    english: "Good work, let's take a short break.",
    anime: "Break Time",
    character: "Saki",
    audioSrc: "",
    category: "Work/Business",
  },
  {
    id: 285,
    japanese: "チームワークが大事ですね。",
    romaji: "Chiimu waaku ga daiji desu ne.",
    english: "Teamwork is important, isn't it?",
    anime: "Team Spirit",
    character: "Nao",
    audioSrc: "",
    category: "Work/Business",
  },
  {
    id: 286,
    japanese: "納期まであと少し、頑張ろう！",
    romaji: "Nouki made ato sukoshi, ganbarou!",
    english: "Just a little more until the deadline, let's do our best!",
    anime: "Deadline Rush",
    character: "Kenta",
    audioSrc: "",
    category: "Work/Business",
  },
  {
    id: 287,
    japanese: "資料作成、手伝いましょうか？",
    romaji: "Shiryou sakusei, tetsudaimashou ka?",
    english: "Shall I help you with the documents?",
    anime: "Support Office",
    character: "Ayaka",
    audioSrc: "",
    category: "Work/Business",
  },
  {
    id: 288,
    japanese: "お先に失礼します。",
    romaji: "Osaki ni shitsurei shimasu.",
    english: "Excuse me, I'm leaving for the day.",
    anime: "After Work",
    character: "Shun",
    audioSrc: "",
    category: "Work/Business",
  },
  {
    id: 289,
    japanese: "この企画、絶対に成功させましょう！",
    romaji: "Kono kikaku, zettai ni seikou sasemashou!",
    english: "Let's make this project a success!",
    anime: "Success Plan",
    character: "Emi",
    audioSrc: "",
    category: "Work/Business",
  },
  {
    id: 290,
    japanese: "上司に報告してきます。",
    romaji: "Joushi ni houkoku shite kimasu.",
    english: "I'll go report to the boss.",
    anime: "Report Time",
    character: "Luna",
    audioSrc: "",
    category: "Work/Business",
  },
  {
    id: 291,
    japanese: "新しいアイデアが浮かびました！",
    romaji: "Atarashii aidea ga ukabimashita!",
    english: "I've got a new idea!",
    anime: "Idea Spark",
    character: "Kai",
    audioSrc: "",
    category: "Work/Business",
  },
  {
    id: 292,
    japanese: "クライアントとの打ち合わせ、よろしくお願いします。",
    romaji: "Kuraianto to no uchiawase, yoroshiku onegaishimasu.",
    english: "Thank you for the meeting with the client.",
    anime: "Client Meeting",
    character: "Mika",
    audioSrc: "",
    category: "Work/Business",
  },
  {
    id: 293,
    japanese: "ランチに行きませんか？",
    romaji: "Ranchi ni ikimasen ka?",
    english: "Shall we go for lunch?",
    anime: "Lunch Break",
    character: "Daichi",
    audioSrc: "",
    category: "Work/Business",
  },
  {
    id: 294,
    japanese: "会議はあと5分で始まります。",
    romaji: "Kaigi wa ato gofun de hajimarimasu.",
    english: "The meeting will start in five minutes.",
    anime: "Meeting Notice",
    character: "Souta",
    audioSrc: "",
    category: "Work/Business",
  },
  {
    id: 295,
    japanese: "今日の目標は達成できましたか？",
    romaji: "Kyou no mokuhyou wa tassei dekimashita ka?",
    english: "Did you achieve today's goal?",
    anime: "Goal Check",
    character: "Yuto",
    audioSrc: "",
    category: "Work/Business",
  },
  {
    id: 296,
    japanese: "お客様第一で頑張りましょう。",
    romaji: "Okyakusama daiichi de ganbarimashou.",
    english: "Let's always put the customer first.",
    anime: "Customer First",
    character: "Shiori",
    audioSrc: "",
    category: "Work/Business",
  },
  {
    id: 297,
    japanese: "プレゼンの練習、付き合ってくれる？",
    romaji: "Purezen no renshuu, tsukiatte kureru?",
    english: "Will you help me practice my presentation?",
    anime: "Presentation Prep",
    character: "Keita",
    audioSrc: "",
    category: "Work/Business",
  },
  {
    id: 298,
    japanese: "今日も一日お疲れさまでした。",
    romaji: "Kyou mo ichinichi otsukaresama deshita.",
    english: "Thank you for your hard work today.",
    anime: "End of Day",
    character: "Emi",
    audioSrc: "",
    category: "Work/Business",
  },
  {
    id: 299,
    japanese: "明日の予定を確認しましょう。",
    romaji: "Ashita no yotei o kakunin shimashou.",
    english: "Let's check tomorrow's schedule.",
    anime: "Schedule Check",
    character: "Luna",
    audioSrc: "",
    category: "Work/Business",
  },
  {
    id: 300,
    japanese: "一緒に働けてよかったです。",
    romaji: "Issho ni hatarakete yokatta desu.",
    english: "I'm glad I could work with you.",
    anime: "Work Friends",
    character: "Rina",
    audioSrc: "",
    category: "Work/Business",
  },
  // 歴史・時代劇（History/Period Drama）
  // 301-320
  {
    id: 301,
    japanese: "拙者、参上つかまつる！",
    romaji: "Sessha, sanjou tsukamatsuru!",
    english: "I have arrived!",
    anime: "Samurai Spirit",
    character: "Jin",
    audioSrc: "",
    category: "History/Period Drama",
  },
  {
    id: 302,
    japanese: "この一刀に全てを賭ける！",
    romaji: "Kono ittou ni subete o kakeru!",
    english: "I stake everything on this single strike!",
    anime: "Blade of Honor",
    character: "Ryo",
    audioSrc: "",
    category: "History/Period Drama",
  },
  {
    id: 303,
    japanese: "殿、どうかご無事で…",
    romaji: "Tono, douka gobuji de...",
    english: "My lord, please be safe...",
    anime: "Castle Shadows",
    character: "Mio",
    audioSrc: "",
    category: "History/Period Drama",
  },
  {
    id: 304,
    japanese: "この国を守るのが我らの使命！",
    romaji: "Kono kuni o mamoru no ga warera no shimei!",
    english: "It is our duty to protect this country!",
    anime: "Warrior's Oath",
    character: "Takumi",
    audioSrc: "",
    category: "History/Period Drama",
  },
  {
    id: 305,
    japanese: "時代が変わっても、心は変わらぬ。",
    romaji: "Jidai ga kawatte mo, kokoro wa kawaranu.",
    english: "Even if times change, my heart will not.",
    anime: "Era's End",
    character: "Saki",
    audioSrc: "",
    category: "History/Period Drama",
  },
  {
    id: 306,
    japanese: "忠義を尽くす、それが武士道。",
    romaji: "Chuugi o tsukusu, sore ga bushidou.",
    english: "To serve with loyalty, that is bushido.",
    anime: "Bushido Path",
    character: "Nao",
    audioSrc: "",
    category: "History/Period Drama",
  },
  {
    id: 307,
    japanese: "この戦、必ず勝ってみせる！",
    romaji: "Kono ikusa, kanarazu katte miseru!",
    english: "I will win this battle, no matter what!",
    anime: "Battlefield Honor",
    character: "Kenta",
    audioSrc: "",
    category: "History/Period Drama",
  },
  {
    id: 308,
    japanese: "姫様、お守りいたします。",
    romaji: "Himesama, omamori itashimasu.",
    english: "Princess, I will protect you.",
    anime: "Princess Guard",
    character: "Ayaka",
    audioSrc: "",
    category: "History/Period Drama",
  },
  {
    id: 309,
    japanese: "夜明けは近い、もう少しの辛抱だ。",
    romaji: "Yoake wa chikai, mou sukoshi no shinbou da.",
    english: "Dawn is near, just a little more patience.",
    anime: "Rebellion Night",
    character: "Shun",
    audioSrc: "",
    category: "History/Period Drama",
  },
  {
    id: 310,
    japanese: "この城は絶対に落とさせぬ！",
    romaji: "Kono shiro wa zettai ni otosasenu!",
    english: "I will never let this castle fall!",
    anime: "Castle Defense",
    character: "Emi",
    audioSrc: "",
    category: "History/Period Drama",
  },
  {
    id: 311,
    japanese: "武士の誇り、ここに示す！",
    romaji: "Bushi no hokori, koko ni shimesu!",
    english: "I will show the pride of a samurai!",
    anime: "Samurai Pride",
    character: "Luna",
    audioSrc: "",
    category: "History/Period Drama",
  },
  {
    id: 312,
    japanese: "戦国の世を生き抜く覚悟はできているか？",
    romaji: "Sengoku no yo o ikinuku kakugo wa dekite iru ka?",
    english: "Are you prepared to survive the warring states era?",
    anime: "Warring Spirits",
    character: "Kai",
    audioSrc: "",
    category: "History/Period Drama",
  },
  {
    id: 313,
    japanese: "義を重んじる、それが我が道。",
    romaji: "Gi o omonjiru, sore ga waga michi.",
    english: "To value justice, that is my way.",
    anime: "Justice Road",
    character: "Mika",
    audioSrc: "",
    category: "History/Period Drama",
  },
  {
    id: 314,
    japanese: "この旗の下に、皆集え！",
    romaji: "Kono hata no moto ni, mina tsudoe!",
    english: "Gather under this flag, everyone!",
    anime: "Flag of Unity",
    character: "Daichi",
    audioSrc: "",
    category: "History/Period Drama",
  },
  {
    id: 315,
    japanese: "敵将、討ち取ったり！",
    romaji: "Tekishou, uchitottari!",
    english: "The enemy general has been defeated!",
    anime: "Victory Shout",
    character: "Souta",
    audioSrc: "",
    category: "History/Period Drama",
  },
  {
    id: 316,
    japanese: "この涙は、未来への誓い。",
    romaji: "Kono namida wa, mirai e no chikai.",
    english: "These tears are a vow for the future.",
    anime: "Vow of Tears",
    character: "Yuto",
    audioSrc: "",
    category: "History/Period Drama",
  },
  {
    id: 317,
    japanese: "我が家の名誉、必ず守る！",
    romaji: "Wagaya no meiyo, kanarazu mamoru!",
    english: "I will protect my family's honor!",
    anime: "Family Honor",
    character: "Shiori",
    audioSrc: "",
    category: "History/Period Drama",
  },
  {
    id: 318,
    japanese: "戦の後には、平和が訪れる。",
    romaji: "Ikusa no ato ni wa, heiwa ga otozureru.",
    english: "After war, peace will come.",
    anime: "Peaceful Era",
    character: "Keita",
    audioSrc: "",
    category: "History/Period Drama",
  },
  {
    id: 319,
    japanese: "この世に生まれたからには、名を残す！",
    romaji: "Kono yo ni umareta kara ni wa, na o nokosu!",
    english: "Since I was born in this world, I will leave my name behind!",
    anime: "Legacy Warriors",
    character: "Emi",
    audioSrc: "",
    category: "History/Period Drama",
  },
  {
    id: 320,
    japanese: "さあ、歴史を作るのは我らだ！",
    romaji: "Saa, rekishi o tsukuru no wa warera da!",
    english: "Come, we are the ones who will make history!",
    anime: "History Makers",
    character: "Rina",
    audioSrc: "",
    category: "History/Period Drama",
  },
  // SF・近未来（Sci-Fi/Futuristic）
  // 321-340
  {
    id: 321,
    japanese: "AIが世界を変える時代が来たね。",
    romaji: "AI ga sekai o kaeru jidai ga kita ne.",
    english: "The era where AI changes the world has come.",
    anime: "Future Code",
    character: "Kai",
    audioSrc: "",
    category: "Sci-Fi/Futuristic",
  },
  {
    id: 322,
    japanese: "宇宙船の準備はできた？",
    romaji: "Uchuusen no junbi wa dekita?",
    english: "Is the spaceship ready?",
    anime: "Star Journey",
    character: "Mio",
    audioSrc: "",
    category: "Sci-Fi/Futuristic",
  },
  {
    id: 323,
    japanese: "この都市はすべてデジタルで動いているんだ。",
    romaji: "Kono toshi wa subete dejitaru de ugoite irun da.",
    english: "This city runs entirely on digital systems.",
    anime: "Cyber City",
    character: "Takumi",
    audioSrc: "",
    category: "Sci-Fi/Futuristic",
  },
  {
    id: 324,
    japanese: "タイムマシンのテスト、いよいよだね。",
    romaji: "Taimu mashin no tesuto, iyoiyo da ne.",
    english: "It's finally time to test the time machine.",
    anime: "Time Travelers",
    character: "Rina",
    audioSrc: "",
    category: "Sci-Fi/Futuristic",
  },
  {
    id: 325,
    japanese: "ロボットと一緒に暮らす未来、楽しみだな。",
    romaji: "Robotto to issho ni kurasu mirai, tanoshimi da na.",
    english: "I'm looking forward to a future living with robots.",
    anime: "Robot Days",
    character: "Souta",
    audioSrc: "",
    category: "Sci-Fi/Futuristic",
  },
  {
    id: 326,
    japanese: "月面基地から地球を見てみたい。",
    romaji: "Getsumen kichi kara chikyuu o mite mitai.",
    english: "I want to see Earth from a moon base.",
    anime: "Lunar Base",
    character: "Nao",
    audioSrc: "",
    category: "Sci-Fi/Futuristic",
  },
  {
    id: 327,
    japanese: "バーチャル世界で冒険しよう！",
    romaji: "Baacharu sekai de bouken shiyou!",
    english: "Let's go on an adventure in the virtual world!",
    anime: "Virtual Quest",
    character: "Kenta",
    audioSrc: "",
    category: "Sci-Fi/Futuristic",
  },
  {
    id: 328,
    japanese: "未来の自分に会えるとしたら、何を聞く？",
    romaji: "Mirai no jibun ni aeru to shitara, nani o kiku?",
    english: "If you could meet your future self, what would you ask?",
    anime: "Future Mirror",
    character: "Ayaka",
    audioSrc: "",
    category: "Sci-Fi/Futuristic",
  },
  {
    id: 329,
    japanese: "地球外生命体とコンタクトできる日が来るかな。",
    romaji: "Chikyuugai seimeitai to kontakuto dekiru hi ga kuru kana.",
    english: "I wonder if the day will come when we can contact extraterrestrial life.",
    anime: "Alien Signal",
    character: "Shun",
    audioSrc: "",
    category: "Sci-Fi/Futuristic",
  },
  {
    id: 330,
    japanese: "このデータを解析すれば、謎が解けるはず。",
    romaji: "Kono deeta o kaiseki sureba, nazo ga tokeru hazu.",
    english: "If we analyze this data, we should be able to solve the mystery.",
    anime: "Data Mystery",
    character: "Emi",
    audioSrc: "",
    category: "Sci-Fi/Futuristic",
  },
  {
    id: 331,
    japanese: "重力制御装置、作動開始！",
    romaji: "Juuryoku seigyo souchi, sadou kaishi!",
    english: "Gravity control device, activate!",
    anime: "Zero Gravity",
    character: "Luna",
    audioSrc: "",
    category: "Sci-Fi/Futuristic",
  },
  {
    id: 332,
    japanese: "未来の乗り物で世界一周しよう。",
    romaji: "Mirai no norimono de sekai isshuu shiyou.",
    english: "Let's travel around the world in a future vehicle.",
    anime: "World Tour 3000",
    character: "Kai",
    audioSrc: "",
    category: "Sci-Fi/Futuristic",
  },
  {
    id: 333,
    japanese: "人工知能と友達になれる時代だよ。",
    romaji: "Jinkou chinou to tomodachi ni nareru jidai da yo.",
    english: "It's an era where you can be friends with AI.",
    anime: "AI Friends",
    character: "Mika",
    audioSrc: "",
    category: "Sci-Fi/Futuristic",
  },
  {
    id: 334,
    japanese: "宇宙エレベーターで星を見に行こう！",
    romaji: "Uchuu erebeetaa de hoshi o mi ni ikou!",
    english: "Let's go see the stars on a space elevator!",
    anime: "Stellar Ride",
    character: "Daichi",
    audioSrc: "",
    category: "Sci-Fi/Futuristic",
  },
  {
    id: 335,
    japanese: "サイボーグ技術が進化してるね。",
    romaji: "Saiboogu gijutsu ga shinka shiteru ne.",
    english: "Cyborg technology is evolving.",
    anime: "Cyborg Future",
    character: "Souta",
    audioSrc: "",
    category: "Sci-Fi/Futuristic",
  },
  {
    id: 336,
    japanese: "火星に住む日も近いかも。",
    romaji: "Kasei ni sumu hi mo chikai kamo.",
    english: "The day we live on Mars might be near.",
    anime: "Mars Colony",
    character: "Yuto",
    audioSrc: "",
    category: "Sci-Fi/Futuristic",
  },
  {
    id: 337,
    japanese: "未来の学校はどんな感じだろう？",
    romaji: "Mirai no gakkou wa donna kanji darou?",
    english: "I wonder what schools will be like in the future?",
    anime: "School 2100",
    character: "Shiori",
    audioSrc: "",
    category: "Sci-Fi/Futuristic",
  },
  {
    id: 338,
    japanese: "ドローン配達、便利すぎる！",
    romaji: "Doron haitatsu, benri sugiru!",
    english: "Drone delivery is so convenient!",
    anime: "Drone Life",
    character: "Keita",
    audioSrc: "",
    category: "Sci-Fi/Futuristic",
  },
  {
    id: 339,
    japanese: "仮想現実で新しい世界を作ろう。",
    romaji: "Kasou genjitsu de atarashii sekai o tsukurou.",
    english: "Let's create a new world in virtual reality.",
    anime: "VR Creators",
    character: "Emi",
    audioSrc: "",
    category: "Sci-Fi/Futuristic",
  },
  {
    id: 340,
    japanese: "未来は自分たちの手で切り開くんだ！",
    romaji: "Mirai wa jibuntachi no te de kirihirakun da!",
    english: "We will carve out the future with our own hands!",
    anime: "Next Generation",
    character: "Rina",
    audioSrc: "",
    category: "Sci-Fi/Futuristic",
  },
  // 名言・決めゼリフ（Famous/Signature Lines）
  // 341-360
  {
    id: 341,
    japanese: "夢を追い続ける限り、終わりはない。",
    romaji: "Yume o oi tsuzukeru kagiri, owari wa nai.",
    english: "As long as you keep chasing your dreams, there is no end.",
    anime: "Dream Chaser",
    character: "Haruto",
    audioSrc: "",
    category: "Famous/Signature Lines",
  },
  {
    id: 342,
    japanese: "諦めなければ、道は開ける。",
    romaji: "Akiramenakereba, michi wa hirakeru.",
    english: "If you don't give up, a path will open.",
    anime: "Never Give Up",
    character: "Mio",
    audioSrc: "",
    category: "Famous/Signature Lines",
  },
  {
    id: 343,
    japanese: "本当の強さは、優しさの中にある。",
    romaji: "Hontou no tsuyosa wa, yasashisa no naka ni aru.",
    english: "True strength lies in kindness.",
    anime: "Kind Heart",
    character: "Takumi",
    audioSrc: "",
    category: "Famous/Signature Lines",
  },
  {
    id: 344,
    japanese: "運命は自分で切り開くものだ。",
    romaji: "Unmei wa jibun de kirihiraku mono da.",
    english: "Fate is something you carve out yourself.",
    anime: "Fate Breaker",
    character: "Rina",
    audioSrc: "",
    category: "Famous/Signature Lines",
  },
  {
    id: 345,
    japanese: "涙は弱さじゃない、強さの証だ。",
    romaji: "Namida wa yowasa janai, tsuyosa no akashi da.",
    english: "Tears are not a sign of weakness, but of strength.",
    anime: "Tears of Courage",
    character: "Souta",
    audioSrc: "",
    category: "Famous/Signature Lines",
  },
  {
    id: 346,
    japanese: "信じる心が、奇跡を起こす。",
    romaji: "Shinjiru kokoro ga, kiseki o okosu.",
    english: "A believing heart creates miracles.",
    anime: "Miracle Maker",
    character: "Nao",
    audioSrc: "",
    category: "Famous/Signature Lines",
  },
  {
    id: 347,
    japanese: "過去は変えられないけど、未来は変えられる。",
    romaji: "Kako wa kaerarenai kedo, mirai wa kaerareru.",
    english: "You can't change the past, but you can change the future.",
    anime: "Time Leap",
    character: "Kenta",
    audioSrc: "",
    category: "Famous/Signature Lines",
  },
  {
    id: 348,
    japanese: "一人じゃない、仲間がいるから。",
    romaji: "Hitori janai, nakama ga iru kara.",
    english: "You're not alone, because you have friends.",
    anime: "Bond of Friends",
    character: "Ayaka",
    audioSrc: "",
    category: "Famous/Signature Lines",
  },
  {
    id: 349,
    japanese: "笑顔は世界を明るくする魔法だ。",
    romaji: "Egao wa sekai o akaruku suru mahou da.",
    english: "A smile is magic that brightens the world.",
    anime: "Smile Magic",
    character: "Shun",
    audioSrc: "",
    category: "Famous/Signature Lines",
  },
  {
    id: 350,
    japanese: "挑戦しなければ、何も始まらない。",
    romaji: "Chousen shinakereba, nanimo hajimaranai.",
    english: "If you don't challenge yourself, nothing will start.",
    anime: "Challenge Spirit",
    character: "Emi",
    audioSrc: "",
    category: "Famous/Signature Lines",
  },
  {
    id: 351,
    japanese: "心の声に正直に生きよう。",
    romaji: "Kokoro no koe ni shoujiki ni ikiyou.",
    english: "Live honestly to your heart's voice.",
    anime: "True Voice",
    character: "Luna",
    audioSrc: "",
    category: "Famous/Signature Lines",
  },
  {
    id: 352,
    japanese: "努力は必ず報われる。",
    romaji: "Doryoku wa kanarazu mukuwareru.",
    english: "Effort will always be rewarded.",
    anime: "Effort Road",
    character: "Kai",
    audioSrc: "",
    category: "Famous/Signature Lines",
  },
  {
    id: 353,
    japanese: "自分を信じて、前に進もう。",
    romaji: "Jibun o shinjite, mae ni susumou.",
    english: "Believe in yourself and move forward.",
    anime: "Forward Step",
    character: "Mika",
    audioSrc: "",
    category: "Famous/Signature Lines",
  },
  {
    id: 354,
    japanese: "どんな闇も、光があれば消える。",
    romaji: "Donna yami mo, hikari ga areba kieru.",
    english: "Any darkness will disappear if there is light.",
    anime: "Light Bringer",
    character: "Daichi",
    audioSrc: "",
    category: "Famous/Signature Lines",
  },
  {
    id: 355,
    japanese: "失敗は成功への第一歩。",
    romaji: "Shippai wa seikou e no daiippo.",
    english: "Failure is the first step to success.",
    anime: "Step Up!",
    character: "Souta",
    audioSrc: "",
    category: "Famous/Signature Lines",
  },
  {
    id: 356,
    japanese: "本気で願えば、夢は叶う。",
    romaji: "Honki de negaeba, yume wa kanau.",
    english: "If you truly wish for it, your dream will come true.",
    anime: "Wish Star",
    character: "Yuto",
    audioSrc: "",
    category: "Famous/Signature Lines",
  },
  {
    id: 357,
    japanese: "出会いは人生を変える力がある。",
    romaji: "Deai wa jinsei o kaeru chikara ga aru.",
    english: "Encounters have the power to change your life.",
    anime: "Life Encounters",
    character: "Shiori",
    audioSrc: "",
    category: "Famous/Signature Lines",
  },
  {
    id: 358,
    japanese: "限界は自分で決めるものじゃない。",
    romaji: "Genkai wa jibun de kimeru mono janai.",
    english: "Limits are not something you decide for yourself.",
    anime: "No Limits",
    character: "Keita",
    audioSrc: "",
    category: "Famous/Signature Lines",
  },
  {
    id: 359,
    japanese: "今日という日は、二度と来ない。",
    romaji: "Kyou to iu hi wa, nidoto konai.",
    english: "Today will never come again.",
    anime: "One Day Only",
    character: "Emi",
    audioSrc: "",
    category: "Famous/Signature Lines",
  },
  {
    id: 360,
    japanese: "未来は自分の手で作るものだ。",
    romaji: "Mirai wa jibun no te de tsukuru mono da.",
    english: "The future is something you create with your own hands.",
    anime: "Future Makers",
    character: "Rina",
    audioSrc: "",
    category: "Famous/Signature Lines",
  },
]
